### ISSUE TITLE
Cтворення заявки декларації керівником на Demo

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#141] opened 2017-10-20 15:12 UTC
=== Internal error response ====  

URL: https://demo.ehealth.world/api/declaration_requests
request: POST
token : dUxjS0RsRERwT3FtdkNvY3pXczNqdz09

## Request Data

[declaration_create_data.txt](https://github.com/ehealth-ua/api-spec/files/1402401/declaration_create_data.txt)

## Employee information

[employee_data .txt](https://github.com/ehealth-ua/api-spec/files/1402402/employee_data.txt)

## Response

{"meta":{"url":"http://demo.ehealth.world/api/declaration_requests","type":"object","request_id":"nff8e75nppu96bnfj1g2kl6drfe7uums","code":500},"error":{"type":"internal_error"}}

**Comment by lymychp** [comment] 2017-10-27 14:48
fixed, please try again

**Comment by superjonh** [comment] 2017-11-07 12:12
@lymychp seems still internal error, is this fix also updated on production?

**Comment by pzhuk** [comment] 2017-11-08 13:19
@superjonh  is this reproduced in production? please share logs

**Comment by lymychp** [comment] 2017-11-08 14:45
@superjonh this issue was related to the env. configuration. Never happened in prod.
I have just successfully created new declaration_request on demo.
Please share request/response date if you still face with this issue.
thanks.

**Comment by superjonh** [comment] 2017-11-08 14:53
@lymychp @pzhuk  okay sure, let me check, if it is still such problem, i will provide request and response logs

**Comment by superjonh** [comment] 2017-11-08 15:11
@lymychp @pzhuk new logs
[InternalErrorLogNew.txt](https://github.com/ehealth-ua/api-spec/files/1454376/InternalErrorLogNew.txt)

**Comment by superjonh** [comment] 2017-11-08 15:28
@pzhuk sended in private messages

**Comment by lymychp** [comment] 2017-11-08 15:35
it looks like there are problems with the encoding in your payload. For example:
`"area": "ÇÀÊÀÐÏÀÒÑÜÊÀ",`

**Comment by superjonh** [comment] 2017-11-08 15:40
@lymychp encoding is by default UTF-8 , but strange by doctor the same request is okay

**Comment by lymychp** [comment] 2017-11-08 16:55
@superjonh the problem is that you are creating declaration between patient and owner
` "employee_id": "7e7aecd9-a8d1-4778-baa8-2b741bdd0e7e",`

Only `employee_id` of doctor should be passed here.

Error code has been fixed on `demo` 12 days ago.

**Comment by superjonh** [comment] 2017-11-08 17:02
@lymychp  and if the legal_entity is registered for example by head physician , then to create and sign declarations he can only if he will register also himself as physician?

**Comment by superjonh** [comment] 2017-11-08 17:08
@lymychp thanks)) could you also provide right response for such requests, internal error doesnt give enought information of wrong data in request

**Comment by lymychp** [comment] 2017-11-08 17:18
anyone who has scope `declaration:write` can create declaration. But declaration can be created only between `employee.type=DOCTOR` and patient. So in your MIS UI you shouldn't allow users  to choose any employee during the declaration creation process. Only employees with type `DOCTOR` should be available to select.

**Comment by superjonh** [comment] 2017-11-08 17:30
@lymychp okay thats clear, all in all owner can perform actions by his scopes ,but in context of declarations he cant be as emloyee_id in request

**Comment by lymychp** [comment] 2017-11-08 18:25
>@lymychp thanks)) could you also provide right response for such requests, internal error doesnt give enought information of wrong data in request

we have fixed that already on demo. But this version hasn't been deployed to prod yet(

**Comment by lymychp** [comment] 2017-11-08 18:25
>@lymychp thanks)) could you also provide right response for such requests, internal error doesnt give enought information of wrong data in request

we have fixed that already on demo. But this version hasn't been deployed to prod yet(

**Comment by superjonh** [comment] 2017-11-08 19:24
@lymychp okay, so just keep me in touch when it will be on prod, or just comment here))

**Closed** 2017-11-21 11:37 UTC
Labels: bug
