### ISSUE TITLE
500 при створенні декларації на пре прод

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#234] opened 2018-02-13 17:28 UTC
## Steps to Reproduce (Repro steps)

- [ ]  https://api.ehealth.world/api/declaration_requests \
- [ ] `{
            "declaration_request" : {
                "person" : {
                    "first_name" : "Евгений",
                    "last_name" : "Губич",
                    "second_name" : "Юрьевичч",
                    "birth_date" : "1987-03-03",
                    "birth_country" : "Украина",
                    "birth_settlement" : "Киев",
                    "gender" : "MALE",
                    "email" : "e.gubich+pat105__3217563h2_2@helsi.me",
                    "secret" : "словоСекретное",
                    "documents" : [ 
                        {
                            "type" : "PASSPORT",
                            "number" : "КМ000006"
                        }
                    ],
                    "addresses" : [ 
                        {
                            "type" : "RESIDENCE",
                            "country" : "UA",
                            "area" : "М.КИЇВ",
                            "settlement" : "КИЇВ",
                            "settlement_type" : "CITY",
                            "settlement_id" : "adaa4abf-f530-461c-bcbf-a0ac210d955b",
                            "building" : "56",
                            "apartment" : "201",
                            "zip" : "02091",
                            "street_type" : "STREET",
                            "street" : "Воздвиженская"
                        }, 
                        {
                            "type" : "REGISTRATION",
                            "country" : "UA",
                            "area" : "М.КИЇВ",
                            "settlement" : "КИЇВ",
                            "settlement_type" : "CITY",
                            "settlement_id" : "adaa4abf-f530-461c-bcbf-a0ac210d955b",
                            "building" : "56",
                            "apartment" : "201",
                            "zip" : "02091",
                            "street_type" : "STREET",
                            "street" : "Воздвиженская"
                        }
                    ],
                    "phones" : [ 
                        {
                            "type" : "MOBILE",
                            "number" : "+380688400757"
                        }
                    ],
                    "authentication_methods" : [ 
                        {
                            "type" : "OTP",
                            "phone_number" : "+380688400757"
                        }
                    ],
                    "emergency_contact" : {
                        "first_name" : "Контакт",
                        "last_name" : "Контактов",
                        "second_name" : "Контактович",
                        "phones" : [ 
                            {
                                "type" : "MOBILE",
                                "number" : "+380680000000"
                            }
                        ]
                    },
                    "confidant_person" : [],
                    "patient_signed" : false,
                    "process_disclosure_data_consent" : true
                },
                "scope" : "family_doctor",
                "employee_id" : "e1362516-7f50-4736-8c04-6cf4e7f94972",
                "division_id" : "f32f8c27-a7a2-4849-a643-7343412287bf"
            }
        }`

## Actual result
- [ ]` {"meta":{"url":"http://api-svc.il/api/declaration_requests","type":"object","request_id":"eb9b2368-6887-4a2a-bcc8-5d26f92df9f4#177835","code":500},"error":{"errors":{"detail":"Internal server error"}}}`

## Expected result
- [ ] http code менше 500.

**Comment by svetavedmed** [comment] 2018-02-14 07:46
the problem is with doctor's speciality. Error fixed on dev with #1766

**Closed by svetavedmed** 2018-02-14 07:46 UTC
